version: '3.2'

services:

  db:
    env_file: ./.env
    command: >-
      /bin/bash -c 
      "while [[ ! -f /docker-entrypoint-initdb.d/latest.sql ]]; do
      echo 'Waiting for database bootstrap...'; sleep 5; done &&
      /entrypoint.sh mysqld"
    entrypoint: ""
    image: mysql/mysql-server:5.7
    restart: always
    volumes:
      - "dbrestore:/docker-entrypoint-initdb.d"

  dbbackup:
    env_file: ./.env
    image: schickling/mysql-backup-s3:latest
    restart: always

  dbrestore:
    env_file: ./.env
    image: quay.io/chiefy/alpine-awscli
    entrypoint: /bin/ash
    command: >-
      -c "aws s3 cp s3://tds-wiki/backup/latest.sql.gz /docker-entrypoint-initdb.d/latest.sql.gz 
      && gunzip /docker-entrypoint-initdb.d/latest.sql.gz"
    volumes:
      - "dbrestore:/docker-entrypoint-initdb.d"

  mediawiki:
    env_file: ./.env
    build: ./mediawiki
    depends_on: 
      - db
    restart: always
    volumes:
      - "wikiwww:/var/www/mediawiki"
      - ./mediawiki/etc/LocalSettings.php:/var/www/mediawiki/LocalSettings.php
      - "s3images:/var/www/mediawiki/images"

  s3sync:
    env_file: ./.env
    image: vladgh/s3sync
    volumes:
      - "s3images:/var/www/mediawiki/images"
    command: sync

  www:
    env_file: ./.env
    build: ./nginx
    depends_on:
      - mediawiki
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/conf/nginx.conf
      - "wikiwww:/var/www/mediawiki:ro"
      - "s3images:/var/www/mediawiki/images:ro"

volumes:
  wikiwww:
  s3images:
  dbrestore: