version: '3.8'

services:

  db:
    env_file: ${CONFIG_ENV:-.env}
    container_name: mediawiki-db
    command: >-
      /bin/bash -c 
      "while [[ ! -f /docker-entrypoint-initdb.d/latest.sql ]]; do
      echo 'Waiting for database bootstrap...'; sleep 5; done &&
      /entrypoint.sh mysqld"
    entrypoint: ""
    image: mysql:5.7-debian
    restart: always
#    ports:
#     - "3306:3306"
    volumes:
      - "dbrestore:/docker-entrypoint-initdb.d"

  dbbackup:
    env_file: ${CONFIG_ENV:-.env}
    image: schickling/mysql-backup-s3:latest
    restart: always

  dbrestore:
    env_file: ${CONFIG_ENV:-.env}
    image: quay.io/chiefy/alpine-awscli
    entrypoint: /bin/ash
    command: >-
      -c "aws s3 cp s3://tds-wiki/backup/lkg.sql.gz /docker-entrypoint-initdb.d/latest.sql.gz 
      && gunzip /docker-entrypoint-initdb.d/latest.sql.gz"
    volumes:
      - "dbrestore:/docker-entrypoint-initdb.d"

  s3sync:
    env_file: ${CONFIG_ENV:-.env}
    build: ./s3sync
    restart: always
    environment:
      - SYNCDIR=/var/www/mediawiki/images
      - INITIAL_DOWNLOAD=force
    volumes:
      - type: volume
        source: s3images
        target: /var/www/mediawiki/images
    command: periodic_upload

  mediawiki:
    env_file: ${CONFIG_ENV:-.env}
    build: ./mediawiki
    container_name: mediawiki-php
    depends_on: 
      - db
    restart: always
    volumes:
      - "wikiwww:/var/www/mediawiki"
      - type: volume
        source: s3images
        target: /var/www/mediawiki/images

  www:
    env_file: ${CONFIG_ENV:-.env}
    build: ./nginx
    container_name: "mediawiki-www"
    environment:
      - VIRTUAL_HOST=${WIKI_HOST}
    depends_on:
      - mediawiki
    ports:
      - "8888:80"
    restart: always
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/conf/nginx.conf
      - "wikiwww:/var/www/mediawiki:ro"
      - type: volume
        source: s3images
        target: /var/www/mediawiki/images

volumes:
  wikiwww:
  s3images: 
  dbrestore:

networks:
  default:
