version: '3.2'

services:

  db:
    env_file: ./common.env
    command: >-
      /bin/bash -c 
      "while [[ ! -f /docker-entrypoint-initdb.d/latest.sql.gz ]]; do
      echo 'Waiting for database bootstrap...'; sleep 5; done &&
      docker-entrypoint.sh mysqld"
    entrypoint: ""
    image: mysql/mysql-server:latest
    restart: always
    volumes:
      - "dbrestore:/docker-entrypoint-initdb.d"

#  dbbackup:
#    env_file: ./common.env
#    image: 'schickling/mysql-backup-s3:latest'
#    links:
#      - db
#    restart: always

  dbrestore:
    env_file: ./common.env
    command: >-
      cp s3://tds-wiki/backup/latest.sql.gz 
      docker-entrypoint-initdb.d/latest.sql.gz
    image: 'quay.io/chiefy/alpine-s3:1.0.1'
    volumes:
      - "dbrestore:/docker-entrypoint-initdb.d"

  mediawiki:
    env_file: ./common.env
    build: ./mediawiki
    restart: always
    volumes:
      - "wikiwww:/var/www/mediawiki"
      - ./mediawiki/etc/LocalSettings.php:/var/www/mediawiki/LocalSettings.php
      - ./mediawiki/skins/components:/var/www/mediawiki/skins/Vector/components
      - "s3images:/var/www/mediawiki/images"

  s3images:
    env_file: ./common.env
    image: amsdard/s3-sync:latest
    volumes:
      - "s3images:/var/www/mediawiki/images"

  www:
    env_file: ./common.env
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/conf/nginx.conf
      - "wikiwww:/var/www/mediawiki"
      - "s3images:/var/www/mediawiki/images"

volumes:
  wikiwww:
  s3images:
  dbrestore: